{
 "title": "gitlab-repository-exporter",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "instance", "query": { "query": "label_values(mr_count, job)" } },
   {
    "name": "branchAuthor",
    "query": {
     "query": "label_values(branch_ttl, committer)"
    }
   },
   { "name": "mrAuthor", "query": { "query": "label_values(mr_ttl, author)" } },
   {
    "name": "project",
    "query": {
     "query": "label_values(mr_count, project_url)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Project", "type": "text", "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 }, "options": { "content": "`${project}`\n" } },
  {
   "title": "Branches per Engineer ",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(branch_ttl{job=~\"$instance\"}) by (committer)",
     "legendFormat": "{{commiter}}"
    }
   ]
  },
  {
   "title": "MRs per Engineer ",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mr_ttl{job=~\"$instance\"}) by (author)",
     "legendFormat": "{{author}}"
    }
   ]
  },
  {
   "title": "Branches | MRs",
   "type": "stat",
   "description": "Branches and MRs quantity per project\n",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "branch_count{job=~\"$instance\"}",
     "legendFormat": "branches"
    },
    {
     "expr": "mr_count{job=~\"$instance\"}",
     "legendFormat": "MRs"
    }
   ]
  },
  {
   "title": "MRs Lifetime",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "targets": [
    {
     "expr": "mr_ttl{job=~\"$instance\", author=~\"$mrAuthor\"}",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Branches Lifetime",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "targets": [
    {
     "expr": "branch_ttl{job=~\"$instance\", committer=~\"$branchAuthor\"}",
     "legendFormat": "{{branch_name}}"
    }
   ]
  },
  {
   "title": "MRs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "group(mr_ttl{job=~\"$instance\", author=~\"$mrAuthor\"}) by (author, branch_name, title, votes_diff)"
    }
   ]
  },
  {
   "title": "Branches",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "group(branch_ttl{job=~\"$instance\", committer=~\"$branchAuthor\"}) by (committer, branch_name)"
    }
   ]
  }
 ]
}